### PR TITLE
Add tags, fix regl-scatter2d entry

### PR DESCRIPTION
**Pull request by dy**
https://github.com/gl-vis/regl-scatter2d/pull/15

### CODE REVIEW

**Comment by archmoj** [comment]
@etpinard Should we test this on Plotly.js?

**Comment by etpinard** [comment]
> Should we test this on Plotly.js?

Yep. I won't have time to get to it today though. You can give it a shot if you want.

**Comment by archmoj** [comment]
OK. I can test it now.

**Comment by etpinard** [comment]
:dancer: from us @dy !

**Comment by dy** [comment]
Published 1.0.5

**Pull request merged**
